# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'  # Puedes cambiar '12.0' por una versión mínima compatible

target 'FirebaseLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseLogin
  pod 'GoogleMaps'

end

